task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ["bbox"]

num_classes: 5
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../../../data/collections/prepared/aip_vip_fisheye_dfine/images
    ann_file: ../../../data/collections/prepared/aip_vip_fisheye_dfine/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: ../../../data/collections/prepared/aip_vip_fisheye_dfine/images
    ann_file: ../../../data/collections/prepared/aip_vip_fisheye_dfine/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
