task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 5
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mlcv3/WorkingSpace/Personal/baotg/AICity25/Track4/data/collections/prepared/original_rfdetr/train
    ann_file: /mlcv3/WorkingSpace/Personal/baotg/AICity25/Track4/data/collections/prepared/original_rfdetr/train/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /mlcv3/WorkingSpace/Personal/baotg/AICity25/Track4/data/collections/prepared/original_rfdetr/valid
    ann_file: /mlcv3/WorkingSpace/Personal/baotg/AICity25/Track4/data/collections/prepared/original_rfdetr/valid/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
