__include__:
  [
  "../dataset/ft.yml",
  "../runtime.yml",
  "include/dataloader_1600.yml",
  "include/optimizer.yml",
  "include/dfine_hgnetv2_1600.yml",
  ]

output_dir: ./trained/finetuned/


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: "B4"
  return_idx: [1, 2, 3]
  freeze_stem_only: True
  freeze_at: 0
  freeze_norm: True

# HybridEncoder:
#   # intra
#   hidden_dim: 384
#   dim_feedforward: 2048

# DFINETransformer:
#   feat_channels: [384, 384, 384]
#   reg_scale: 8


optimizer:
  type: AdamW
  params:
    - params: "^(?=.*backbone)(?!.*norm|bn).*$"
      lr: 0.0000125
    - params: "^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$"
      weight_decay: 0.

  lr: 0.00025
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epochs: 100 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 90
  collate_fn:
    stop_epoch: 90
    ema_restart_decay: 0.9999
    base_size_repeat: 4

ema:
  warmups: 0

lr_warmup_scheduler:
  warmup_duration: 0

train_dataloader:
  total_batch_size: 8

val_dataloader:
  total_batch_size: 8
